### ISSUE TITLE
I think this is a "fork" of an article, you could put the author credits

### ISSUE THREAD

**Issue by andremion** [nisrulz/UploadToMavenCentral#1]
This is the link of the article:
[https://android.jlelse.eu/the-complete-guide-to-creating-an-android-library-46628b7fc879#.ht6ujcnr1](https://android.jlelse.eu/the-complete-guide-to-creating-an-android-library-46628b7fc879#.ht6ujcnr1)

**Comment by nisrulz** [comment]
Well this repository is the example code for my own blog post : http://crushingcode.co/publish-your-android-library-via-mavencentral/

I just checked your provided link and would like to add that it looks similar , but I wrote everything based of my own experience. I have further more blog posts about how you can publish to Jcenter and Jitpack in the series that i wrote.

I should add backlinks to my own blogpost to the readme if that would make sense. 
Thank you

**Comment by andremion** [comment]
I just said that because they are quite similar and the provided post was published nine months before yours.
But that's OK, it's up to you.
Thanks.
